# Clock signal
set_property PACKAGE_PIN W5 [get_ports clock_100Mhz]       
 set_property IOSTANDARD LVCMOS33 [get_ports clock_100Mhz]
set_property PACKAGE_PIN T2 [get_ports Reset]     
        set_property IOSTANDARD LVCMOS33 [get_ports Reset]
#seven-segment LED display
        set_property PACKAGE_PIN W7 [get_ports {Display[6]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[6]}]
        set_property PACKAGE_PIN W6 [get_ports {Display[5]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[5]}]
        set_property PACKAGE_PIN U8 [get_ports {Display[4]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[4]}]
        set_property PACKAGE_PIN V8 [get_ports {Display[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[3]}]
        set_property PACKAGE_PIN U5 [get_ports {Display[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[2]}]
        set_property PACKAGE_PIN V5 [get_ports {Display[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[1]}]
        set_property PACKAGE_PIN U7 [get_ports {Display[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Display[0]}]
        set_property PACKAGE_PIN U2 [get_ports {Anodes[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[0]}]
        set_property PACKAGE_PIN U4 [get_ports {Anodes[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[1]}]
        set_property PACKAGE_PIN V4 [get_ports {Anodes[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[2]}]
        set_property PACKAGE_PIN W4 [get_ports {Anodes[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[3]}]